apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
stringData:
  MONGODB_URI: "mongodb://appuser:apppassword@mongo-svc.mongo-db.svc.cluster.local:27017/ecommerce?authSource=ecommerce"
  JWT_SECRET: "f830c3db2a4d89f78b30793eeb6b2cf9e8819189994bdacea9c16dc7f6789c90a631f7119f6974e034712610d5da3e8c373911c965f596030638fcb5934b958"
  FRONTEND_URL: "http://front-svc.frontend.svc.cluster.local:8080"
  PORT: "5000"
