apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
  namespace: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts: []
  #     secretName: ingress-tls
  rules:
    #host: lb-382757127.us-east-1.elb.amazonaws.com
  -  http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front-svc
            port: 
              number: 8080