name: ci-the-app
on:
  workflow_dispatch:


jobs:

  # ===================== FRONTEND =====================
  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.0

      - name: Set up Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22.21.1'

      - name: Install Dependencies
        working-directory: ./ecommerce-frontend
        run: npm install

      - name: Run Semgrep Code Analysis
        uses: semgrep/semgrep-action@v1
        with:
          config: "p/ci"
          path: ./ecommerce-frontend
          generateSarif: "true"

      - name: Trivy Dependency Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: ./ecommerce-frontend

      - name: Build Docker Image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/frontend:latest ./ecommerce-frontend/.

      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: image
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/front:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/front:latest



  # ===================== BACKEND =====================
  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest
    needs: frontend   
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.0

      - name: Set up Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22.21.1'

      - name: Install Dependencies
        working-directory: ./ecommerce-backend
        run: npm install

      - name: Run Semgrep Code Analysis
        uses: semgrep/semgrep-action@v1
        with:
          config: "p/ci"
          path: ./ecommerce-backend
          generateSarif: "true"

      - name: Trivy Dependency Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: ./ecommerce-backend

      - name: Build Docker Image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/back:latest ./ecommerce-backend/.

      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: image
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/back:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/back:latest

          
